#!/usr/bin/env bash
# Task 3
for pid in /proc/[0-9]*; do
       pid_num="${pid##*/}"

       if [ -r "$pid/comm" ]; then
        name=$(<"$pid/comm")
        if [[ "$name" == *bash* ]]; then
            echo "$pid_num $name"
        fi
    fi
done
